### ISSUE TITLE
Add possibility to merge old character data with new fusion server data

### ISSUE THREAD

**Issue by xavi-ortega** [HafisCZ/sf-tools#113]
**Description**
Add possibility to merge old character data with new fusion server data

**Additional context:**
I have been using SFTools for few years, and I had all the data of my main account in the `s1.sfgame.es` server, but now the server was merged, and it's creating a new set of data in `f5.sfgame.net`.
![image](https://github.com/HafisCZ/sf-tools/assets/14571996/53605424-1f2a-4b42-baa2-0cc068de2424)

Could it be possible to merge both characters to have only one source of true?

**Comment by HafisCZ** [comment]
I had asked Playa repeatedly to give us way to see the previous server and player ID after merge but so far nothing. It's quite complicated because of the amount of potential dependencies but I think I will add a manual way soon. However it probably won't be without issues (guild data may be just impossible to make work).

**Comment by HafisCZ** [comment]
Hey @xavi-ortega, a manual merge prototype is available on https://beta.sftools.mar21.eu/. You will need to go to Players or Guilds tab and check the checkboxes of the players/ guilds you need to merge, then click Merge / split characters or guilds in bottom right.

**Comment by xavi-ortega** [comment]
Tested and working. Can't wait to try it in prod 😄

**Comment by HafisCZ** [comment]
Merged
